### ISSUE TITLE
There was an error fetching images

### ISSUE THREAD

**Issue by DarkIsDude** [gilbitron/Splashify#12]
Hi,

When I open the application, I have "There was an error fetching images"...
I'm on MAC.

**Comment by gilbitron** [comment]
Hi. Are you connected to the internet? When you try again does the same thing happen?

**Comment by DarkIsDude** [comment]
Hi. Yes, I'm connected to internet. Where can I found log for this app? Maybe a Firewall?
When I try again, I have always this message. I'm not alone, French User from an article: http://www.macg.co/logiciels/2017/01/splashify-pour-trouver-des-fonds-decran-facilement-97164#comments

**Comment by DarkIsDude** [comment]
Thanks, that's ok now!
