### ISSUE TITLE
为什么壁纸不能一直显示(Why can't wallpaper always show)

### ISSUE THREAD

**Issue by tommysj** [gilbitron/Splashify#13]
为什么每次壁纸选择完后，重启WINDOWS，壁纸就会变成选择之前的壁纸。
(Why every time after the wallpaper selection, restart WINDOWS, wallpaper will become the choice before the wallpaper.)

my english is poor , sorry.

Splashify  is the best wallpaper software i used.

thanks.

**Comment by gilbitron** [comment]
Duplicate of #9.
